server:
  port: 8888
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    # 一个实体类对应两张表覆盖
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  shardingsphere:
    mode:
      type: Memory
    props:
      sql:
        show: true
    datasource:
      enabled: true
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      rules:
        # 配置读写分离
        readwrite-splitting:
          data-sources:
            ds_ms:
              type: Static
              props:
                write-data-source-name: master
                read-data-source-names: slave
            load-balancer-name: round_robin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
#  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#    cache-enabled: false
  global-config:
    db-config:
      # mybatis-plus主键生成策略，3.1.0版本支持的和3.5.3.1版本支持的不一样
      id-type: AUTO # AUTO: 数据库ID自增, INPUT: 用户输入ID, ID_WORKER: 全局唯一ID, UUID: 全局唯一ID
      update-strategy: not_null # all: 所有字段, not_null: 非NULL字段

# 事务管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug