server:
  port: 8888

spring:
  profiles:
    active: single

  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  #  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #    cache-enabled: false
  global-config:
    db-config:
      # mybatis-plus主键生成策略，3.1.0版本支持的和3.5.3.1版本支持的不一样
      id-type: AUTO # AUTO: 数据库ID自增, INPUT: 用户输入ID, ID_WORKER: 全局唯一ID, UUID: 全局唯一ID
      update-strategy: not_null # all: 所有字段, not_null: 非NULL字段

# 事务管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
