spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    # 一个实体类对应两张表覆盖，不能动
    allow-bean-definition-overriding: true
  shardingsphere:
    mode.type: Memory
    props:
      sql.show: true
    datasource:
      enabled: true
      names: db-user, db-order-0, db-order-1
      db-user:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.41.95.194:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      db-order-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.41.95.194:3306/slave_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      db-order-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://101.37.253.225:3306/slave_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin


    # 垂直分片, 逻辑表和真实节点的表名
    sharding:
      tables:
        # 用户表
        sys_user:
          key-generator:
            column: id
            type: SNOWFLAKE

          actualDataNodes: db-user.sys_user_$->{0..1}
          databaseStrategy:
            none:
          tableStrategy:
            # inline表达式
            inline:
              sharding-column: id
              algorithm-expression: sys_user_$->{id % 2}
        # 订单表
        # 根据user_id分库, 根据order_no分表
        sys_order:
          key-generator:
            column: id
            type: SNOWFLAKE
          actualDataNodes: db-order-$->{0..1}.sys_order_$->{0..1}
          databaseStrategy:
            inline:
              sharding-column: user_id
              algorithm-expression: db-order-$->{user_id % 2}
          tableStrategy:
            inline:
              sharding-column: order_no
              algorithm-expression: sys_order_$->{Math.abs(order_no.hashCode() % 2)}
        # 订单详情表
        # order_item表
        sys_order_item:
          key-generator:
            column: id
            type: SNOWFLAKE
          actualDataNodes: db-order-$->{0..1}.sys_order_item_$->{0..1}
          databaseStrategy:
            inline:
              sharding-column: user_id
              algorithm-expression: db-order-$->{user_id % 2}
          tableStrategy:
            inline:
              sharding-column: order_no
              algorithm-expression: sys_order_item_$->{Math.abs(order_no.hashCode() % 2)}
        # 广播表
        sys_dict:
          actualDataNodes: db-user.sys_dict, db-order-$->{0..1}.sys_dict
          databaseStrategy:
            none:
          tableStrategy:
            none:

      # 配置绑定表,这样就不会做多余的联表查询
      binding-tables[0]: sys_order, sys_order_item

      # 配置广播表
      broadcast-tables[0]: sys_dict
