server:
  port: 8888
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  shardingsphere:
    mode:
      type: Memory
    props:
      sql:
        show: true
    datasource:
      enabled: true
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.41.95.194:3306/read_write_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.41.95.194:13306/read_write_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: admin
        password: pwd@admin
      rules:
        readwrite-splitting:
          data-sources:
            ds_ms:
              type: Static
              props:
                write-data-source-name: ds0
                read-data-source-names: ds1
            load-balancer-name: round_robin
#            read-write-datasource:
#              static-strategy:
#                # 写库数据源名称
#                write-data-source-name: ds0
#                # 读库数据源列表，多个从数据源用逗号分隔
#                read-data-source-names: ds1
#              # 负载均衡算法名称
#              load-balancer-name: round_robin
#          # 负载均衡算法配置
#          load-balancers:
#            round_robin:
#              # 负载均衡算法类型
#              type: ROUND_ROBIN
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#    username: root
#    password: cyqcw.@4
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
#  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#    cache-enabled: false
  global-config:
    db-config:
      id-type: AUTO # AUTO: 数据库ID自增, INPUT: 用户输入ID, ID_WORKER: 全局唯一ID, UUID: 全局唯一ID
      update-strategy: not_null # all: 所有字段, not_null: 非NULL字段

# 事务管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug